name: dart_bip21
description: A BIP21 compatible URL encoding package developed for DartLang.
version: 1.0.0
homepage: https://github.com/dart-bitcoin-lib/dart-bip21
repository: https://github.com/dart-bitcoin-lib/dart-bip21
issue_tracker: https://github.com/dart-bitcoin-lib/dart-bip21/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
